### ISSUE TITLE
Remove line to use in Browser

### ISSUE THREAD

**Issue by jonalxh** [juspay/card-validator#11]
Hi, I've been using card-validator in a learning project and I've noticed that to use it in browser, with dist/validator.js is necessary to delete the last line in the file mentioned:

     module.exports = cardValidator;

Please check and update it.

Thanks.

**Comment by boazjohn** [comment]
@jonalxh bower itself is being phased out and they recommend alternatives like yarn or webpack. https://bower.io

I think for npm, yarn etc, this line is required.

**Comment by jonalxh** [comment]
Thanks.
