### ISSUE TITLE
Update Diners Club International Regex

### ISSUE THREAD

**Issue by nileshr** [juspay/card-validator#2]
Some of the Diners club international cards are not getting identified. The regex could be updated from /^36/ to /^3([689]|09)/ ( Source - https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_.28IIN.29 )

**Comment by ramanathanrv** [comment]
Hi, thanks for pointing out. If you can make the change, please send a pull request. Else, kindly wait for a day for us to make the change.

**Comment by nileshr** [comment]
@ramanathanrv Any updates on this?
